- hosts: master
  tasks:
  - name: Install Calico
    shell: |
      kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock
      export KUBECONFIG=/etc/kubernetes/admin.conf
      kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock
      export KUBECONFIG=/etc/kubernetes/admin.conf
      curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml -O
      kubectl apply -f calico.yaml
    register: calico
    
  - debug:
      msg: "{{calico.stdout}}"
  - name: Copy to multiple hosts
    copy:
     content: "{% for host in ansible_play_hosts_all %}{{ hostvars[host].calico.stdout }}\n{% endfor %}"
     dest: kubeadm.log
    delegate_to: localhost
    run_once: true
  
  - name: Get the token for joining the worker nodes
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join

  - debug:
      msg: "{{ kubernetes_join.stdout }} --cri-socket=unix:///var/run/cri-dockerd.sock "
      
  - name: Copy the message
    copy: 
     content: "{{ kubernetes_join.stdout }} --cri-socket=unix:///var/run/cri-dockerd.sock "
     dest: /tmp/kubernetes_join
    delegate_to: localhost
    run_once: true
