- hosts: worker 
  tasks:
  - name: Copy join command from Ansiblehost to the worker nodes
    copy:
       src: /tmp/kubernetes_join
       dest: /tmp/kubernetes_join
       mode: 0777

  - name: Join the Worker nodes to the cluster.
    command: sh /tmp/kubernetes_join
    register: joined_or_not

  - debug: 
      msg: "{{ joined_or_not.stdout }}"

